[sources.sql_database.credentials]
drivername =
database =
password =
username =
host =
port =

[destination.postgres.credentials]
database = "db_workshop" # please set me up!
password = "admin" # please set me up!
username = "carlos" # please set me up!
host = "localhost" # please set me up!
port = 5432
connect_timeout = 15
