services:
  db:
    image: postgres:15
    environment:
      PGUSER: carlos
      POSTGRES_USER: carlos
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_workshop

    ports:
      - 5432:5432
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    networks:
      - metanet1
  
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: db_workshop
      MB_DB_PORT: 5432
      MB_DB_USER: carlos
      MB_DB_PASS: admin
      MB_DB_HOST: db
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  metanet1:
    driver: bridge

volumes:
  postgres_data: {}
